### ISSUE TITLE
A bit stuck with using this in VB

### ISSUE THREAD

**Issue by GreenTurtwig** [PoroCYon/PokeApi.NET#12]
Managed to build and reference it in VB but got a bit stuck after that since it's in C# on the README.
This sort of thing is all new to me and would like some help. I'll mainly be setting labels as the Pokemon's stats e.t.c when the user has entered it's name into a textbox. :-)

**Comment by PoroCYon** [comment]
See [this](https://msdn.microsoft.com/en-us/library/hh191443.aspx) for info about async/await.

Here's an example in VB (I hardly ever use it, but it should look like this):

```vb
Import System
Import PokeAPI

' gets the instance as a task
Dim ThePokemon_Task As Task(Of Pokemon) = Pokemon.GetInstanceAsync(395)

' gets the instance asynchronously, to be used in another async ~~method~~ sub/function
Dim ThePokemon_Async = Await ThePokemon_Task

' runs the task on the current thread
Dim ThePokemon As Pokemon = ThePokemon_Task.RunSynchronously()

' or in one line:
Dim ThePokemon_ = Pokemon.GetInstanceAsync("Lucario").RunSynchronously()

' all of these can be used in one line, obviously
```

**Comment by GreenTurtwig** [comment]
Thank you! :-)
Got it working now after I read through the MSDN page and (sort of) figured out how it works. Still don't understand `RunSynchronously` but I got my program to work regardless and it now brings up the Pokemon's information. :-D

**Comment by PoroCYon** [comment]
A `Task<T>` wraps a piece of code so it can be executed on different threads (imagine it containing a delegate to a method), RunSynchonously() just makes it run on the current one, nothing fancy (i.e. `return InnerMethod();`). `Task`s are useful because they can be composed in multiple ways.

**Comment by GreenTurtwig** [comment]
Ah, great. Makes more sense now. :-)
Bit of a shame I cant/dont know how to use the v2 database though with all the gen 6 Pokemon.

**Comment by PoroCYon** [comment]
I don't think v2 is stable already..?

**Comment by GreenTurtwig** [comment]
No I don't think it is, good thing I've seen people working on it though. Hopefully it will come in the following months though considering its been almost a year. :-)
