### ISSUE TITLE
Move project to Portable library

### ISSUE THREAD

**Issue by vfabregat** [PoroCYon/PokeApi.NET#6]
I think that could be a cool change, this api could be used from Windows Phone, Xamarin or another platform.

The following items have problems:

* `IOrderedDictionary`
* `Bitmap` could be replaced with `byte[]`
* `WebClient` could be replace with [this package](https://www.nuget.org/packages/Microsoft.Net.Http)
* `IDictionary` in `JsonData` class this is a problematic item because is from JsonLite, but could be replaced with Json.net or chance the `IDictionary` by a `IDicionary<TKey, TValue>`
* `ApplicationException` same as above item. But this could be replace it with `Exception`
* Replace all `MemoryStream.Close` to `Dispose` [here](http://cureos.blogspot.com.es/2014/06/pcl-tips-and-tricks-extension-methods.html) and [here](http://cureos.blogspot.com.es/search/label/pcl-tips-tricks) more information.
* `Type.GetInterface` [here](http://stackoverflow.com/questions/20524263/portable-class-library-reflection) more information

**Comment by PoroCYon** [comment]
Done most of it, but a cleanup is needed. I will readd the XmlDoc afterwards.

**Comment by vfabregat** [comment]
Cool! awesome changes! I like the refactoring.

**Comment by PoroCYon** [comment]
I guess it's done (except for the XmlDoc, but most things are documented), so I'll close this issue.
